#!/usr/bin/python

import sys
from math import *


# ---------
# functions
# ---------

def get_input():
	inputs = dict()
	input_lines = int(raw_input())
	count = 0
	while count < input_lines:
		line = raw_input()
		key = line[0]
		value = int(line[2:])
		inputs[key] = value
		count += 1
	inputs['C'] = radians(90)
	return inputs

def calc_triangle(triangle):
	num_sides = 0
	num_angles = 0
	for key in triangle.iterkeys():
		if key == 'a' or key == 'b' or key == 'c':
			num_sides += 1
		elif key == 'A' or key == 'B' or key == 'C':
			num_angles += 1
	
	if num_sides == 1:
		print 'hello'
	elif num_sides == 2:
		if not triangle.has_key('a'):
			triangle['a'] = 0
		elif not triangle.has_key('b'):
			triangle['b'] = 0
		elif not triangle.has_key('c'):
			triangle['c'] = 0
	
	return triangle

def print_outputs(outputs):
	for key, value in outputs.items():
		print str(key) + '=' + str(value)


# ----
# main
# ----

outputs = calc_triangle(get_input())
print_outputs(outputs)
